### ISSUE TITLE
Invite emails: Expiration of the invites

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/jquest#95] opened 2016-11-30 10:04 UTC
Currently the users reported that the invites expire but we don't know when.
Would it be possible to:
- configure the invite so that they never expire
or
- display a field in a user overview: invite expired (yes/no)

**Comment by pirhoo** [comment] 2016-12-01 09:54
Everything I tested  tends to confirm that there is no expiration delay for the invitation. The only reason that can invalidate an invitation token is if someone sent another one. I suppose its a duplicate of #94 then.

**Closed** 2016-12-05 17:15 UTC
Labels: need testing
